sudo: required
services:
  - docker
script:
  - cd sandbox
  - docker build -f Dockerfile -t codeforpoznan/django-onboarding:latest .
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" = false ]; then
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD;
      docker push codeforpoznan/django-onboarding;
    fi
